#! /usr/bin/env python3

# Date:         Mon Nov 29 11:49:41 AM CST 2021
# Description:  Create a Gallery

from modules.Tools import *
import sys

if len(sys.argv) != 2:
    print(
        'Usage: {} <collection-path>\n\n\te.g: collection-path\n\t\t- img-folder-1 \n\t\t... \n\t\t- img-folder-n'
        .format(sys.argv[0])
    )
    sys.exit(0)

scrollable('handmade/custom/downloads')
grid('handmade/custom/downloads')
