#! /usr/bin/env python3

# Date:         Mon Nov 29 11:49:41 AM CST 2021
# Description:  Create a Gallery

import os

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Gallery</title>
    <style>
        body, img{
            padding: 0;
            margin: 0;
            border: 0;
            text-align: center;
            font-size: 0;
        }

       @media only screen and (max-width: 1080px) {
            img{
                width: 100%;
            }
        }
    </style>
</head>
<body bgcolor="#131315">
holder
</body>
</html>
"""

for chapter in os.listdir('chapters'):
    imgs = ''
    for page in sorted(os.listdir('chapters/{}'.format(chapter))):
        if page[-3:] != 'jpg':
            continue
        imgs = imgs + '\n    <img src="{}"></img>'.format(page)
    with open('chapters/{}/gallery.html'.format(chapter), 'w') as f:
        f.write( html.replace('holder', imgs + '\n') )

print('file://{}/chapters/'.format(os.getcwd()))
