#! /usr/bin/env python3

# Date:         Mon Nov 29 02:53:12 AM CST 2021
# Description:  Download Silent War chapters from manhwa365

from bs4 import BeautifulSoup
from pwn import *
import requests
import os

prefix = 'https://manhwa365.com/webtoon/silent-war-english'
chapters = range(150, 154 + 1)
download_path = './chapters'
timeout = 15

p = log.progress('Downloading')

for chapter in chapters:
    os.makedirs('{}/{:03}/'.format(download_path, chapter), exist_ok=True)
    p.status('Chapter {} - 0.00%'.format(chapter))
    url = '{}/chapter-{}/'.format(prefix, chapter)

    try:
        r = requests.get(url, timeout=timeout)
    except:
        p.failure('Timeout in chapter {}'.format(chapter))
        sys.exit(1)
    if not r.ok:
        p.failure('Connection error in chapter {}'.format(chapter))
        sys.exit(1)

    bs = BeautifulSoup(r.text, 'html.parser')

    images = [img['data-src'].strip() for img in bs.find_all('img', {'class': 'wp-manga-chapter-img'})]

    for i, img_url in enumerate(images):
        try:
            r = requests.get(img_url, timeout=timeout)
        except:
            p.failure('Timeout in chapter {} page {}'.format(chapter, i+1))
            sys.exit(1)
        if not r.ok:
            p.failure('Connection error in chapter {} page {}'.format(chapter, i+1))
            sys.exit(1)

        with open('{}/{:03}/{:02}.jpg'.format(download_path, chapter, i+1), 'wb') as f:
            f.write(r.content)
        total = len(images)
        p.status('Chapter {} - {:.2f}%'.format( chapter, (i+1)/total*100 ) )

p.success('Done')
